# Generated by Django 5.1.5 on 2025-01-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='availible',
            new_name='available',
        ),
    ]
